/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/heads/head_1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
let headPathToPreLoad = './assets/models/heads/head_1.glb';


export function Head(props) {
  headPathToPreLoad = './assets/models/heads/head_' + props.index + '.glb';
  console.log("🚀 ~ Head ~ headPathToPreLoad:", headPathToPreLoad)
  const { nodes, materials } = useGLTF(headPathToPreLoad)
  return (
    <group {...props} dispose={null} scale={0.04} position={[0, 1, 0]}>
      <mesh geometry={nodes.shape.geometry} material={nodes.shape.material} />
    </group>
  )
}

useGLTF.preload(headPathToPreLoad)

