/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/noses/nose_1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
<<<<<<< HEAD
let pathToPreLoad = '/assets/models/noses/nose_1.glb';
import * as THREE from 'three'

export function Nose(props) {
  pathToPreLoad = '/assets/models/noses/nose_' + props.index + '.glb';
=======
let pathToPreLoad = '/mii-maker-demo/assets/models/noses/nose_1.glb';
import * as THREE from 'three'

export function Nose(props) {
  pathToPreLoad = '/mii-maker-demo/assets/models/noses/nose_' + props.index + '.glb';
>>>>>>> main
  const { nodes, materials } = useGLTF(pathToPreLoad)
  nodes.shape.material.color = {...nodes.shape.color, ...props.color}
  return (
    <group {...props} dispose={null} scale={0.04} position={[0, 1.8, 1]}>
      <mesh geometry={nodes.shape.geometry} material={nodes.shape.material} />
    </group>
  )
}

useGLTF.preload(pathToPreLoad)
